/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stdint.h"
#include "stdio.h"
#define RCC_BASE 0x40021000
#define GPIO_Port_A  0x40010800
#define RCC_ABP2ENR (*(volatile uint32_t *) (RCC_BASE+0x018))
#define GPIOA_CRL (*(volatile uint32_t *) (GPIO_Port_A+0x00))
#define GPIOA_CRH (*(volatile uint32_t *) (GPIO_Port_A+0x04))
#define GPIOA_IDR (*(volatile uint32_t *) (GPIO_Port_A+0x08))
#define GPIOA_ODR (*(volatile uint32_t *) (GPIO_Port_A+0x0C))
#define GPIO_Port_B  0x40010C00
#define GPIOB_CRL (*(volatile uint32_t *) (GPIO_Port_B+0x00))
#define GPIOB_CRH (*(volatile uint32_t *) (GPIO_Port_B+0x04))
#define GPIOB_IDR (*(volatile uint32_t *) (GPIO_Port_B+0x08))
#define GPIOB_ODR (*(volatile uint32_t *) (GPIO_Port_B+0x0C))
void delay(unsigned int a){
	unsigned int i ,j ;
	for(i=0; i<a; i++){
		for(j=0; j<256; j++);
	}
}

void CLOCK_INIT()
{
	RCC_ABP2ENR |=(1<<2);//enable clock for GPIO PORTA
	RCC_ABP2ENR |=(1<<3);//enble clock for GPIO PORTB
}
void GPIO_INIT()
{


	//set portA pin 13 as input floating
	GPIOA_CRH &=~(0b1111<<20);
	GPIOA_CRH |=(0b0100<<20);
	//set portA pin 1 as input floating
	GPIOA_CRL &=~(0b1111<<4);
	GPIOA_CRL |=(0b0100<<4);
	//set portB pin 1 as output mode (push-pull),max speed 2MHZ
	GPIOB_CRL &=~(0b1111<<4);
	GPIOB_CRL |=(0b0010<<4);
	// set portB pin 13 as output mode(push-pull),max speed 2MHZ
	GPIOB_CRH &=~(0b1111<<20);
	GPIOB_CRH |=(0b0010<<20);
}


int main(void)
{
	CLOCK_INIT();
	GPIO_INIT();
	while(1)
	{
		if(((GPIOA_IDR&(1<<1))>>1)==0)
		{
			GPIOB_ODR^=(1<<1);//single pressing
			while(((GPIOA_IDR&(1<<1))>>1)==0);
		}
		if(((GPIOA_IDR&(1<<13))>>13)==1)
		{
			GPIOB_ODR^=(1<<13);//multi pressing

		}
		delay(1);

	}
}
